import type { VenuePreset } from "@/lib/types";

export const SINGAPORE_VENUES: VenuePreset[] = [
  {
    id: "mbs-ballroom",
    name: "Marina Bay Sands Ballroom (section)",
    kind: "ballroom",
    areaSqft: 8000,
    lengthM: 30,
    depthM: 25,
    ceilingM: 7,
    power: "heavy",
    powerNote: "High load available; coordinate power with venue engineering.",
    inHouseAudioLikely: true,
  },
  {
    id: "rws-ballroom",
    name: "Resorts World Sentosa Ballroom",
    kind: "ballroom",
    areaSqft: 6000,
    lengthM: 28,
    depthM: 20,
    ceilingM: 6,
    power: "heavy",
    powerNote: "In-house AV often available — confirm before bringing full PA.",
    inHouseAudioLikely: true,
  },
  {
    id: "suntec-hall",
    name: "Suntec Convention Hall",
    kind: "expo",
    areaSqft: 10000,
    lengthM: 40,
    depthM: 30,
    ceilingM: 8,
    power: "heavy",
    powerNote: "High power and truck access typical for expo halls.",
    inHouseAudioLikely: false,
  },
  {
    id: "orchard-wedding",
    name: "Orchard hotel wedding ballroom (small)",
    kind: "wedding_ballroom",
    areaSqft: 2500,
    lengthM: 18,
    depthM: 13,
    ceilingM: 4,
    power: "medium",
    powerNote: "Often has in-house audio — ask before deploying external PA.",
    inHouseAudioLikely: true,
  },
  {
    id: "community-hall",
    name: "Community / CC multipurpose hall",
    kind: "multipurpose",
    areaSqft: 3000,
    lengthM: 20,
    depthM: 14,
    ceilingM: 4.5,
    power: "light",
    powerNote: "Limited circuits — plan loads carefully.",
    inHouseAudioLikely: false,
  },
  {
    id: "school-mph",
    name: "School multipurpose hall",
    kind: "multipurpose",
    areaSqft: 4000,
    lengthM: 24,
    depthM: 15,
    ceilingM: 6,
    power: "medium",
    powerNote: "Typical school power limits; confirm distribution boards.",
    inHouseAudioLikely: false,
  },
  {
    id: "tented-outdoor",
    name: "Tented outdoor (enclosed)",
    kind: "outdoor_tented",
    areaSqft: 5000,
    lengthM: 25,
    depthM: 18,
    ceilingM: 4,
    power: "generator",
    powerNote: "Generator often required for tented outdoor events.",
    inHouseAudioLikely: false,
  },
  {
    id: "open-field",
    name: "Open outdoor field / FOW-style",
    kind: "outdoor_open",
    areaSqft: 8000,
    lengthM: 35,
    depthM: 25,
    ceilingM: null,
    power: "generator",
    powerNote: "Generator + weather plan required; outdoor LED for daytime.",
    inHouseAudioLikely: false,
  },
];

export function getVenueById(id: string): VenuePreset | undefined {
  return SINGAPORE_VENUES.find((v) => v.id === id);
}
